version: '3.4'

services:
  dane_db:
    image: mariadb:10.3.7
    container_name: dane_prueba
    hostname: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootdane123*
      MYSQL_DATABASE: dbencuesta
      MYSQL_USER: userpruebas
      MYSQL_PASSWORD: userpurebas123*
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3308:3306
    restart: always

