# Generated by Django 4.2.1 on 2023-07-11 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('chapter', models.CharField(choices=[('1', 'Cápitulo 1'), ('2', 'Cápitulo 2'), ('3', 'Cápitulo 3'), ('4', 'Cápitulo 4'), ('5', 'Cápitulo 5'), ('6', 'Cápitulo 6'), ('7', 'Cápitulo 7'), ('8', 'Cápitulo 8'), ('9', 'Cápitulo 9')], default=1, max_length=100)),
                ('question', models.CharField(max_length=1000)),
                ('instruction', models.CharField(choices=[('1', 'Escriba una respuesta.'), ('2', 'Por favor seleccione solo una opción'), ('3', 'Puede seleccionar más de una opción')], default=1, max_length=100)),
                ('type', models.CharField(choices=[('1', 'Input'), ('2', 'Radio'), ('3', 'Check')], max_length=30)),
                ('isRequired', models.BooleanField()),
                ('isInteger', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('response', models.CharField(blank=True, max_length=1000, null=True, verbose_name='res')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.questions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=2000)),
                ('redirectQuestion', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.questions')),
            ],
        ),
    ]
